const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '..', 'src', 'AppCore.tsx');
const lines = fs.readFileSync(filePath, 'utf8').split('\n');
const originalCount = lines.length;
console.log(`Original: ${originalCount} lines\n`);

// Each block defined by 1-indexed start-end lines (inclusive)
// These are the inline JSX blocks that need to be replaced with component calls

const blocks = [
  {
    tab: 'communications',
    component: 'CommunicationsHubPage',
    startLine: 7908,
    endLine: 8189,
    props: [
      'commsTotalAttention={commsTotalAttention}',
      'commsChannelsActive={commsChannelsActive}',
      'fetchAllSentEmails={fetchAllSentEmails}',
      'fetchAllWhatsAppMessages={fetchAllWhatsAppMessages}',
      'fetchAllCallLogs={fetchAllCallLogs}',
      'fetchTeamMessages={fetchTeamMessages}',
      'openCommunicationTool={openCommunicationTool}',
      'commsHighPriority={commsHighPriority}',
      'commsRepliesWaiting={commsRepliesWaiting}',
      'commsBrandStatus={commsBrandStatus}',
      'emailAttentionCount={emailAttentionCount}',
      'emailBrandRows={emailBrandRows}',
      'whatsappAttentionCount={whatsappAttentionCount}',
      'whatsappBrandRows={whatsappBrandRows}',
      'dueCallActionCount={dueCallActionCount}',
      'callBrandRows={callBrandRows}',
      'teamGlobalUnreadCount={teamGlobalUnreadCount}',
      'usersList={usersList}',
      'user={user}',
      'visibleNotificationItems={visibleNotificationItems}',
      'activeBrands={activeBrands}',
      'getBrandIntegrationFor={getBrandIntegrationFor}',
      'getEmailAccountsForIntegration={getEmailAccountsForIntegration}',
      'isWhatsAppCloudConfigured={isWhatsAppCloudConfigured}',
      'whatsappNumbers={whatsappNumbers}',
    ],
  },
  {
    tab: 'intelligence',
    component: 'IntelligencePage',
    startLine: 8195,
    endLine: 8467,
    props: [
      'allCrmLeads={allCrmLeads}',
      'leads={leads}',
      'sequences={sequences}',
      'websiteAnalyticsSummary={websiteAnalyticsSummary}',
      'portfolioOpportunities={portfolioOpportunities}',
      'globalDuplicateLeadGroups={globalDuplicateLeadGroups}',
      'dataCleanupSearch={dataCleanupSearch}',
      'setDataCleanupSearch={setDataCleanupSearch}',
      'activeBrands={activeBrands}',
      'managedBrands={managedBrands}',
      'handleSelectBrand={handleSelectBrand}',
      'todayCommand={todayCommand}',
      'portfolioCounts={portfolioCounts}',
      'scanPortfolioOpportunities={scanPortfolioOpportunities}',
      'portfolioSaving={portfolioSaving}',
      'showDataCleanupStudio={showDataCleanupStudio}',
      'setShowDataCleanupStudio={setShowDataCleanupStudio}',
      'usersList={usersList}',
      'allSentEmails={allSentEmails}',
      'allWhatsAppMessages={allWhatsAppMessages}',
      'allCallLogs={allCallLogs}',
      'getGlobalLeadActivityCount={getGlobalLeadActivityCount}',
      'reviewPortfolioOpportunity={reviewPortfolioOpportunity}',
      'setActiveIntegrationChannel={setActiveIntegrationChannel}',
      'setActiveTab={setActiveTab}',
    ],
  },
  {
    tab: 'dashboard',
    component: 'DashboardPage',
    startLine: 8469,
    endLine: 9139,
    props: [
      'allCrmLeads={allCrmLeads}',
      'leads={leads}',
      'brandIntegrations={brandIntegrations}',
      'activeBrands={activeBrands}',
      'managedBrands={managedBrands}',
      'setIntegrationBrandId={setIntegrationBrandId}',
      'setActiveIntegrationChannel={setActiveIntegrationChannel}',
      'setActiveTab={setActiveTab}',
      'setupGuideCollapsed={setupGuideCollapsed}',
      'setSetupGuideCollapsed={setSetupGuideCollapsed}',
      'leadSources={leadSources}',
      'websiteAnalyticsSites={websiteAnalyticsSites}',
      'usersList={usersList}',
      'handleSelectBrand={handleSelectBrand}',
      'portfolioCounts={portfolioCounts}',
      'portfolioCollapsed={portfolioCollapsed}',
      'setPortfolioCollapsed={setPortfolioCollapsed}',
      'scanPortfolioOpportunities={scanPortfolioOpportunities}',
      'portfolioSaving={portfolioSaving}',
      'dismissPendingPortfolioOpportunities={dismissPendingPortfolioOpportunities}',
      'portfolioForm={portfolioForm}',
      'setPortfolioForm={setPortfolioForm}',
      'savePortfolioRule={savePortfolioRule}',
      'portfolioRules={portfolioRules}',
      'portfolioOpportunities={portfolioOpportunities}',
      'reviewPortfolioOpportunity={reviewPortfolioOpportunity}',
      'getGlobalLeadActivityCount={getGlobalLeadActivityCount}',
      'duplicateLeadIds={duplicateLeadIds}',
      'todayCommand={todayCommand}',
      'emailAttentionCount={emailAttentionCount}',
      'whatsappAttentionCount={whatsappAttentionCount}',
      'dueCallActionCount={dueCallActionCount}',
      'teamGlobalUnreadCount={teamGlobalUnreadCount}',
      'brandOperatingMetrics={brandOperatingMetrics}',
      'commandMetrics={commandMetrics}',
      'resetCommandMetrics={resetCommandMetrics}',
      'dashboardDensity={dashboardDensity}',
      'setDashboardDensity={setDashboardDensity}',
      'getCommandMetricValue={getCommandMetricValue}',
      'openCommandMetricModal={openCommandMetricModal}',
      'deleteCommandMetric={deleteCommandMetric}',
      'getNextActionForLead={getNextActionForLead}',
      'getLeadBrand={getLeadBrand}',
      'setSelectedBrand={setSelectedBrand}',
      'setSelectedBrandForEmail={setSelectedBrandForEmail}',
      'setActiveEmailLead={setActiveEmailLead}',
      'setSelectedBrandForWhatsApp={setSelectedBrandForWhatsApp}',
      'setActiveWhatsAppLead={setActiveWhatsAppLead}',
      'setSelectedBrandForCalls={setSelectedBrandForCalls}',
      'setActiveCallLead={setActiveCallLead}',
      'setActiveLead={setActiveLead}',
      'loadLeadDetailsHistory={loadLeadDetailsHistory}',
      'portfolioLeaderboard={portfolioLeaderboard}',
      'countUniquePeopleForBrand={countUniquePeopleForBrand}',
      'brandIntelligenceBreakdowns={brandIntelligenceBreakdowns}',
      'isSectionVisible={isSectionVisible}',
      'toggleSection={toggleSection}',
      'setIntelligenceBuilderOpen={setIntelligenceBuilderOpen}',
      'intelligenceBuilderOpen={intelligenceBuilderOpen}',
      'intelligenceForm={intelligenceForm}',
      'setIntelligenceForm={setIntelligenceForm}',
      'editingIntelligenceId={editingIntelligenceId}',
      'setEditingIntelligenceId={setEditingIntelligenceId}',
      'showToast={showToast}',
      'isFollowUpDue={isFollowUpDue}',
      'getSnapshotCardValue={getSnapshotCardValue}',
      'snapshotCards={snapshotCards}',
      'handleDeleteSnapshotCard={handleDeleteSnapshotCard}',
      'snapshotForm={snapshotForm}',
      'setSnapshotForm={setSnapshotForm}',
      'handleAddSnapshotCard={handleAddSnapshotCard}',
      'getBrandSegmentOptions={getBrandSegmentOptions}',
      'getBrandStageOptions={getBrandStageOptions}',
      'getStageColor={getStageColor}',
      'getLeadMetricRawValue={getLeadMetricRawValue}',
      'isMeaningfulMetricValue={isMeaningfulMetricValue}',
      'getLeadIdentityKeyForBrand={getLeadIdentityKeyForBrand}',
      'setBrandIntelligenceBreakdowns={setBrandIntelligenceBreakdowns}',
      'DEFAULT_INTELLIGENCE_BREAKDOWNS={DEFAULT_INTELLIGENCE_BREAKDOWNS}',
      'setSelectedStageFilter={setSelectedStageFilter}',
      'setSelectedCustomFieldFilter={setSelectedCustomFieldFilter}',
      'setSelectedSegmentFilter={setSelectedSegmentFilter}',
    ],
  },
  {
    tab: 'calls',
    component: 'CallsPage',
    startLine: 9144,
    endLine: 9399,
    props: [
      'diallerLeadsList={diallerLeadsList}',
      'selectedBrandForCalls={selectedBrandForCalls}',
      'setSelectedBrandForCalls={setSelectedBrandForCalls}',
      'callStageFilter={callStageFilter}',
      'setCallStageFilter={setCallStageFilter}',
      'activeCallLead={activeCallLead}',
      'setActiveCallLead={setActiveCallLead}',
      'leadCalls={leadCalls}',
      'getBrandIntegrationFor={getBrandIntegrationFor}',
      'handleSelectCommunications={handleSelectCommunications}',
      'managedBrands={managedBrands}',
      'activeBrands={activeBrands}',
      'setDiallerLead={setDiallerLead}',
      'setCallNotes={setCallNotes}',
      'setCallFollowUpDate={setCallFollowUpDate}',
      'getBrandStageOptions={getBrandStageOptions}',
      'setActiveLead={setActiveLead}',
      'loadLeadDetailsHistory={loadLeadDetailsHistory}',
      'isCalling={isCalling}',
      'diallerLead={diallerLead}',
      'callSeconds={callSeconds}',
      'handleEndSimulatedCall={handleEndSimulatedCall}',
      'handleStartSimulatedCall={handleStartSimulatedCall}',
      'callOutcome={callOutcome}',
      'setCallOutcome={setCallOutcome}',
      'callDuration={callDuration}',
      'setCallDuration={setCallDuration}',
      'callFollowUpDate={callFollowUpDate}',
      'messageTemplates={messageTemplates}',
      'applyTemplateVars={applyTemplateVars}',
      'callNotes={callNotes}',
      'handleLogCallSubmit={handleLogCallSubmit}',
      'callSaving={callSaving}',
      'setActiveTab={setActiveTab}',
      'setIntegrationBrandId={setIntegrationBrandId}',
      'integrationBrandId={integrationBrandId}',
      'setActiveIntegrationChannel={setActiveIntegrationChannel}',
    ],
  },
  {
    tab: 'email-tracking',
    component: 'EmailTrackingPage',
    startLine: 9404,
    endLine: 10699,
    props: [
      'leads={leads}',
      'selectedBrandForEmail={selectedBrandForEmail}',
      'setSelectedBrandForEmail={setSelectedBrandForEmail}',
      'emailStageFilter={emailStageFilter}',
      'setEmailStageFilter={setEmailStageFilter}',
      'activeEmailLead={activeEmailLead}',
      'setActiveEmailLead={setActiveEmailLead}',
      'allSentEmails={allSentEmails}',
      'fetchAllSentEmails={fetchAllSentEmails}',
      'getBrandIntegrationFor={getBrandIntegrationFor}',
      'emailConnections={emailConnections}',
      'getEmailAccountsForIntegration={getEmailAccountsForIntegration}',
      'selectedEmailAccountId={selectedEmailAccountId}',
      'setSelectedEmailAccountId={setSelectedEmailAccountId}',
      'outlookSyncing={outlookSyncing}',
      'gmailSyncing={gmailSyncing}',
      'customMailboxSyncing={customMailboxSyncing}',
      'syncOutlookMessages={syncOutlookMessages}',
      'syncGmailReplies={syncGmailReplies}',
      'syncCustomMailboxMessages={syncCustomMailboxMessages}',
      'emailProviderFilter={emailProviderFilter}',
      'setEmailProviderFilter={setEmailProviderFilter}',
      'emailMailboxFilter={emailMailboxFilter}',
      'setEmailMailboxFilter={setEmailMailboxFilter}',
      'getEmailActionSummary={getEmailActionSummary}',
      'isEmailActionable={isEmailActionable}',
      'getEmailActionBucket={getEmailActionBucket}',
      'emailSearchQuery={emailSearchQuery}',
      'setEmailSearchQuery={setEmailSearchQuery}',
      'emailPage={emailPage}',
      'setEmailPage={setEmailPage}',
      'selectedMailboxEmailIds={selectedMailboxEmailIds}',
      'setSelectedMailboxEmailIds={setSelectedMailboxEmailIds}',
      'selectedEmailLogId={selectedEmailLogId}',
      'setSelectedEmailLogId={setSelectedEmailLogId}',
      'emailReplyBody={emailReplyBody}',
      'setEmailReplyBody={setEmailReplyBody}',
      'directEmailOpen={directEmailOpen}',
      'setDirectEmailOpen={setDirectEmailOpen}',
      'directEmailTo={directEmailTo}',
      'setDirectEmailTo={setDirectEmailTo}',
      'directEmailName={directEmailName}',
      'setDirectEmailName={setDirectEmailName}',
      'emailSubject={emailSubject}',
      'setEmailSubject={setEmailSubject}',
      'emailContent={emailContent}',
      'setEmailContent={setEmailContent}',
      'emailTemplateSel={emailTemplateSel}',
      'setEmailTemplateSel={setEmailTemplateSel}',
      'emailAttachments={emailAttachments}',
      'setEmailAttachments={setEmailAttachments}',
      'emailSending={emailSending}',
      'setEmailSending={setEmailSending}',
      'prepareEmailAttachments={prepareEmailAttachments}',
      'sendDirectBrandEmail={sendDirectBrandEmail}',
      'showToast={showToast}',
      'messageTemplates={messageTemplates}',
      'EMAIL_TEMPLATES={EMAIL_TEMPLATES}',
      'applyEmailTemplateVars={applyEmailTemplateVars}',
      'addEmailAttachmentFiles={addEmailAttachmentFiles}',
      'sendTrackedEmail={sendTrackedEmail}',
      'handleSelectCommunications={handleSelectCommunications}',
      'managedBrands={managedBrands}',
      'activeBrands={activeBrands}',
      'setActiveLead={setActiveLead}',
      'handleSelectBrand={handleSelectBrand}',
      'loadLeadDetailsHistory={loadLeadDetailsHistory}',
      'handleDeleteEmail={handleDeleteEmail}',
      'handleBulkDeleteMailboxEmails={handleBulkDeleteMailboxEmails}',
      'markEmailReadInCrm={markEmailReadInCrm}',
      'isInboundCrmEmail={isInboundCrmEmail}',
      'sanitizeEmailHtml={sanitizeEmailHtml}',
      'openingAttachmentKey={openingAttachmentKey}',
      'handleEmailAttachment={handleEmailAttachment}',
      'handleEmailAction={handleEmailAction}',
      'emailProviderMode={emailProviderMode}',
      'setEmailProviderMode={setEmailProviderMode}',
      'setIntegrationBrandId={setIntegrationBrandId}',
      'integrationBrandId={integrationBrandId}',
      'setActiveIntegrationChannel={setActiveIntegrationChannel}',
    ],
  },
  {
    tab: 'whatsapp-tracking',
    component: 'WhatsAppPage',
    startLine: 10702,
    endLine: 11005,
    props: [
      "activeTab={'whatsapp-tracking'}",
      'leads={leads}',
      'selectedBrandForWhatsApp={selectedBrandForWhatsApp}',
      'setSelectedBrandForWhatsApp={setSelectedBrandForWhatsApp}',
      'allWhatsAppMessages={allWhatsAppMessages}',
      'fetchAllWhatsAppMessages={fetchAllWhatsAppMessages}',
      'waContactSearch={waContactSearch}',
      'setWaContactSearch={setWaContactSearch}',
      'waPickerSearch={waPickerSearch}',
      'setWaPickerSearch={setWaPickerSearch}',
      'activeWhatsAppLead={activeWhatsAppLead}',
      'setActiveWhatsAppLead={setActiveWhatsAppLead}',
      'getBrandIntegrationFor={getBrandIntegrationFor}',
      'isWhatsAppCloudConfigured={isWhatsAppCloudConfigured}',
      'whatsappNumbers={whatsappNumbers}',
      'setWhatsappNumbers={setWhatsappNumbers}',
      'handleSelectCommunications={handleSelectCommunications}',
      'managedBrands={managedBrands}',
      'activeBrands={activeBrands}',
      'setDirectWhatsAppOpen={setDirectWhatsAppOpen}',
      'directWhatsAppOpen={directWhatsAppOpen}',
      'setWaDashboardMessage={setWaDashboardMessage}',
      'waDashboardMessage={waDashboardMessage}',
      'sendDirectWhatsApp={sendDirectWhatsApp}',
      'showToast={showToast}',
      'waContactPickerOpen={waContactPickerOpen}',
      'setWaContactPickerOpen={setWaContactPickerOpen}',
      'waPickerSelectedIds={waPickerSelectedIds}',
      'setWaPickerSelectedIds={setWaPickerSelectedIds}',
      'directWhatsAppNumber={directWhatsAppNumber}',
      'setDirectWhatsAppNumber={setDirectWhatsAppNumber}',
      'directWhatsAppName={directWhatsAppName}',
      'setDirectWhatsAppName={setDirectWhatsAppName}',
      'setSelectedBrand={setSelectedBrand}',
      'setSelectedLeadIds={setSelectedLeadIds}',
      'setBulkWhatsAppMessage={setBulkWhatsAppMessage}',
      'setBulkWhatsAppProgress={setBulkWhatsAppProgress}',
      'setBulkWhatsAppModalOpen={setBulkWhatsAppModalOpen}',
      'getFollowUpStatus={getFollowUpStatus}',
      'countUniquePeopleForBrand={countUniquePeopleForBrand}',
      'saveWhatsAppNumbers={saveWhatsAppNumbers}',
      'waSavingSettings={waSavingSettings}',
      'setWaSavingSettings={setWaSavingSettings}',
      'resetWhatsAppTemplateForm={resetWhatsAppTemplateForm}',
      'getWhatsAppTemplatesForBrand={getWhatsAppTemplatesForBrand}',
      'startEditWhatsAppTemplate={startEditWhatsAppTemplate}',
      'deleteWhatsAppTemplate={deleteWhatsAppTemplate}',
      'waTemplateName={waTemplateName}',
      'setWaTemplateName={setWaTemplateName}',
      'waTemplateMessage={waTemplateMessage}',
      'setWaTemplateMessage={setWaTemplateMessage}',
      'saveWhatsAppTemplate={saveWhatsAppTemplate}',
      'waTemplateEditingId={waTemplateEditingId}',
      'waTemplateSel={waTemplateSel}',
      'setWaTemplateSel={setWaTemplateSel}',
      'applyTemplateVars={applyTemplateVars}',
      'fetchLeadsForEmailBrand={fetchLeadsForEmailBrand}',
      'setActiveTab={setActiveTab}',
      'setIntegrationBrandId={setIntegrationBrandId}',
      'setActiveIntegrationChannel={setActiveIntegrationChannel}',
    ],
  },
  {
    tab: 'team-chat',
    component: 'TeamChatPage',
    startLine: 11399,
    endLine: 11703,
    props: [
      "activeTab={'team-chat'}",
      'usersList={usersList}',
      'user={user}',
      'activeTeamDmId={activeTeamDmId}',
      'setActiveTeamDmId={setActiveTeamDmId}',
      'teamRecipientId={teamRecipientId}',
      'setTeamRecipientId={setTeamRecipientId}',
      'teamChatSubTab={teamChatSubTab}',
      'setTeamChatSubTab={setTeamChatSubTab}',
      'teamMessageText={teamMessageText}',
      'setTeamMessageText={setTeamMessageText}',
      'teamFiles={teamFiles}',
      'setTeamFiles={setTeamFiles}',
      'teamDmSearch={teamDmSearch}',
      'setTeamDmSearch={setTeamDmSearch}',
      'teamUnreadOnly={teamUnreadOnly}',
      'setTeamUnreadOnly={setTeamUnreadOnly}',
      'teamPresenceStatus={teamPresenceStatus}',
      'setTeamPresenceStatus={setTeamPresenceStatus}',
      'profilePicture={profilePicture}',
      'teamGlobalUnreadCount={teamGlobalUnreadCount}',
      'fetchTeamMessages={fetchTeamMessages}',
      'getTeamThreadMessages={getTeamThreadMessages}',
      'getTeamThreadUnreadCount={getTeamThreadUnreadCount}',
      'getTeamMessageDateKey={getTeamMessageDateKey}',
      'formatTeamPreviewTime={formatTeamPreviewTime}',
      'formatTeamDateDivider={formatTeamDateDivider}',
      'formatTeamTime={formatTeamTime}',
      'handleDeleteTeamMessage={handleDeleteTeamMessage}',
      'renderTeamMessageContent={renderTeamMessageContent}',
      'handleSendTeamMessage={handleSendTeamMessage}',
      'formatTeamDraft={formatTeamDraft}',
      'addTeamFiles={addTeamFiles}',
      'startTeamCall={startTeamCall}',
      'teamPosting={teamPosting}',
      'handleSelectCommunications={handleSelectCommunications}',
      'setUserNotesOpen={setUserNotesOpen}',
      'fetchTeamNotes={fetchTeamNotes}',
      'teamMessages={teamMessages}',
    ],
  },
];

// Add LoginPage (special: if/return block, not a tab block)
const loginBlock = {
  tab: '__login__',
  component: 'LoginPage',
  startLine: 7655, // "  // LOGIN SCREEN"
  endLine: 7823,   // "  }"
  isLoginPage: true,
  props: [],
};
blocks.push(loginBlock);

// Process from last to first to maintain line numbers
const sortedBlocks = [...blocks].sort((a, b) => b.startLine - a.startLine);

let result = [...lines]; // clone array

for (const block of sortedBlocks) {
  // Convert 1-indexed to 0-indexed
  const startIdx = block.startLine - 1;
  const endIdx = block.endLine - 1;
  
  // Verify the start line matches
  const firstLine = result[startIdx];
  
  const removedLines = endIdx - startIdx + 1;
  
  let replacement;
  
  if (block.isLoginPage) {
    // LoginPage: replace the entire if (!user) block
    replacement = [
      '  // LOGIN SCREEN',
      '  if (!user) {',
      '    return <LoginPage onLoginSuccess={(u) => setUser(u)} />;',
      '  }',
    ];
  } else {
    // Tab block: verify start line
    if (!firstLine.includes(`activeTab === '${block.tab}'`)) {
      console.log(`WARNING: ${block.component} start line mismatch at line ${block.startLine}: "${firstLine.trim().substring(0, 60)}"`);
      continue;
    }
    
    // Build replacement
    const propsArr = block.props;
    let propLines = [];
    for (let i = 0; i < propsArr.length; i += 2) {
      const pair = propsArr.slice(i, i + 2).join(' ');
      propLines.push('              ' + pair);
    }
    
    replacement = [
      `          {activeTab === '${block.tab}' && (`,
      `            <${block.component}`,
      ...propLines,
      '            />',
      '          )}',
    ];
  }
  
  result.splice(startIdx, removedLines, ...replacement);
  console.log(`${block.component}: lines ${block.startLine}-${block.endLine} (${removedLines} lines) -> ${replacement.length} lines`);
}

const newContent = result.join('\n');
const newCount = result.length;
console.log(`\nResult: ${originalCount} -> ${newCount} lines (removed ${originalCount - newCount})`);

fs.writeFileSync(filePath, newContent, 'utf8');
console.log('File written successfully');
